- name: add docker gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg  # TODO export to var
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
      
- name: add docker apt repository
  apt_repository:
    repo: deb [arch="amd64" signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    filename: /etc/apt/sources.list.d/docker.list

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: start docker service
  service:
    name: docker
    state: started
    enabled: true

- name: set docker group for main user
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes