---
- hosts: all
  become: true

  vars:

  pre_tasks:
  - name: install core apt packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - apt-transport-https
        - python3
        - python3-pip

  - name: install core python packages
    pip:
      name:
        - docker
  
  roles:
    - docker

- hosts: jenkinscontroller
  become: true

  vars:
    jenkins_controller_version: 2.401.2-lts-jdk11
    jenkins_controller_default_user: jenkins
    jenkins_controller_default_password: jenkins
    jenkins_agent_ssh_private_key_path: ../resources/ec2-eu-central-1-jenkins-agent.pem  # TODO dynamic generation

  roles:
    - jenkins_controller
  
