---
- hosts: all
  become: true

  vars:


  pre_tasks:
  - name: install core apt packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - apt-transport-https
  
  roles:
    - docker  